In [1]:
%load_ext autoreload
# %autoreload 2

In [6]:
%autoreload 2
from src import matriz_aumentada, gauss_jordan,eliminacion_gaussiana

A = [
    [2,1,-1],
    [1,0,2]
]
eliminacion_gaussiana(A)

[02-18 16:32:59][INFO][josue] 2026-02-18 16:32:59.300717
[02-18 16:32:59][INFO][josue] 
[[ 1.  0.  2.]
 [ 0.  1. -5.]]
Total sumas/restas: 5
Total mult/div: 7


array([ 2., -5.])

In [7]:
Ab = [
    [2,1,-1,0],
    [1,0,2,5],
    [1,-2,4,5]
]
eliminacion_gaussiana(Ab)

[02-18 16:33:11][INFO][josue] 
[[  1.   0.   2.   5.]
 [  0.   1.  -5. -10.]
 [  0.  -2.   2.   0.]]
[02-18 16:33:11][INFO][josue] 
[[  1.   0.   2.   5.]
 [  0.   1.  -5. -10.]
 [  0.   0.  -8. -20.]]
Total sumas/restas: 16
Total mult/div: 20


array([0. , 2.5, 2.5])

In [8]:
Ab = [
    [1,2,3,4,1],
    [2,5,6,7,-2],
    [3,6,8,9,3],
    [4,7,9,10,4]
]
eliminacion_gaussiana(Ab)


[02-18 16:37:10][INFO][josue] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[02-18 16:37:10][INFO][josue] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7. -4.]]
[02-18 16:37:10][INFO][josue] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2. -4.]]
Total sumas/restas: 35
Total mult/div: 42


array([ 3., -6.,  6., -2.])

# Resolver

In [3]:
import logging
from sys import stdout
from datetime import datetime
import os

logging.basicConfig(
    level=logging.INFO,
    format=f"[%(asctime)s][%(levelname)s][{os.environ.get('USERNAME')}] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[01-28 23:06:13][INFO][Jonathan Zea] 2026-01-28 23:06:13.785684


In [4]:
import numpy as np


# ####################################################################
def inv_matrix(A: np.ndarray) -> np.ndarray:
    """Inversión de una matriz cuadrada mediante método de Gauss-Jordan.
    ## Parameters
    ``A``: matriz cuadrada de tamaño n x n.

    ## Return
    ``A_inv``: matriz inversa de A.
    """
    # COMPLETAR
    # Debe basarse en la función gauss_jordan
    pass

## Ejemplos
* Ejemplo 1

In [5]:
# La matriz A =
A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
# tiene como inversa
# A_inv =[[ 0.5, -0.5, -1.5,  1.5],
#        [-0.5,  1.5, -1.5,  0.5],
#        [-1.5, -1.5,  3.5, -1.5],
#        [ 1.5,  0.5, -1.5,  0.5]]
inv_matrix(A)

* Ejemplo 2

In [6]:
# La matriz A =
A = [
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
]
# tiene como inversa
# A_inv =[[-34.,  31.,  52., -20.],
#         [ 19., -17., -29.,  11.],
#         [ 12., -11., -18.,   7.],
#         [  1.,  -1.,  -2.,   1.]]
inv_matrix(A)

## Ejercicios

* Ejercicio 1

In [7]:
A = [[2, -3], [-1, 1]]
inv_matrix(A)

* Ejercicio 2

In [8]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
inv_matrix(A)

* Ejercicio 3

In [9]:
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],
]
inv_matrix(A)

* Ejercicio 4

In [10]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
inv_matrix(A)